receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 100ms
    send_batch_size: 1
    send_batch_max_size: 10

exporters:
  elasticsearch:
    endpoints: ["http://elasticsearch:9200"]
    user: elastic
    password: nkiATsBHHFsQvVeY3Zk6
    traces_index: "otel-v1-traces"
    logs_index: "otel-v1-logs"
    mapping:
      mode: "ecs"
    retry:
      enabled: true
      max_requests: 5
      initial_interval: 100ms
      max_interval: 1m

  debug:
    verbosity: detailed


extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    logs:
      level: debug
    metrics:
      level: detailed
  extensions: [health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, elasticsearch]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch]

