services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - bootstrap.memory_lock=true
      - ELASTIC_PASSWORD=MG0nM0*BmGzOXxFAi59
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "0.0.0.0:9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - elasticnet

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICE_ACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS1zZXJ2aWNlLXRva2VuOlQxalZwLUdvUlRpNGJsSlJwbXpNTmc
      - xpack.encryptedSavedObjects.encryptionKey=12345678901234567890123456789012
      - xpack.security.encryptionKey=abcdefghijabcdefghijabcdefghijab
      - xpack.reporting.encryptionKey=zxcvbnmlkjhgfdsaqwertyuiopasdfgh
    ports:
      - "0.0.0.0:5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elasticnet

volumes:
  esdata:

networks:
  elasticnet:
    external: true